language: node_js
node_js:
  - 10.15.0
services:
  - mongodb
before_install:
  - cd ./backend
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
