var CONST_APP_ID = "";
var CONST_KEY = "";
var CONST_SECRET = "";
var CONST_CLUSTER = "";

module.exports = {CONST_APP_ID:CONST_APP_ID, CONST_KEY:CONST_KEY, CONST_SECRET:CONST_SECRET, CONST_CLUSTER:CONST_CLUSTER};  